#!/usr/bin/env python3
"""
Generate pose line-number index for XL-pose_merged.txt and NSFW_sex_categories/.

Two views:
  1. Merged view: every line in merged, Sex entries annotated with subfolder source
  2. Category view: each subfolder file's entries with merged line number cross-reference

Usage:
    python pose_index.py              # generate pose_index.txt
    python pose_index.py --check      # check if index is stale (by line counts)
"""

import os
import sys
from collections import defaultdict

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CAT_DIR = os.path.join(BASE, 'NSFW_sex_categories')
SFW_FILE = os.path.join(BASE, 'XL-pose_SFW_clean.txt')
SOLO_FILE = os.path.join(BASE, 'XL-pose_NSFW_solo-nude.txt')
SEX_FILE = os.path.join(BASE, 'XL-pose_NSFW_sex.txt')
MERGED_FILE = os.path.join(BASE, 'XL-pose_merged.txt')
INDEX_FILE = os.path.join(BASE, 'pose_index.txt')

PREVIEW_LEN = 100


def load_lines(path):
    """Return list of stripped non-empty lines."""
    if not os.path.exists(path):
        return []
    with open(path, 'r', encoding='utf-8') as f:
        return [l.strip() for l in f if l.strip()]


def build_source_map(cat_dir):
    """Return {entry_text: [(cat_name, line_number), ...]} from subfolder files."""
    src_map = defaultdict(list)
    for fname in sorted(os.listdir(cat_dir)):
        if not fname.endswith('.txt'):
            continue
        cat_name = fname.replace('.txt', '')
        fpath = os.path.join(cat_dir, fname)
        with open(fpath, 'r', encoding='utf-8') as f:
            for i, line in enumerate(f, 1):
                line = line.strip()
                if not line:
                    continue
                src_map[line].append((cat_name, i))
    return src_map


def generate():
    sfw = load_lines(SFW_FILE)
    solo = load_lines(SOLO_FILE)
    merged = load_lines(MERGED_FILE)

    sfw_start = 1
    sfw_end = sfw_start + len(sfw) - 1
    solo_start = sfw_end + 1
    solo_end = solo_start + len(solo) - 1
    sex_start = solo_end + 1
    sex_end = sex_start + len(merged) - len(sfw) - len(solo) - 1

    src_map = build_source_map(CAT_DIR)

    out = []
    out.append(f'# pose_index.txt — generated by program/pose_index.py')
    out.append(f'# Rebuild: python program/pose_index.py')
    out.append(f'')
    out.append(f'## XL-pose_merged.txt  [{len(merged)} entries]')
    out.append(f'')

    # ── SFW ──
    out.append(f'### SFW  L{sfw_start}-L{sfw_end}  [{len(sfw)} entries]')
    out.append(f'')
    for i, line in enumerate(sfw):
        preview = line[:PREVIEW_LEN] + ('...' if len(line) > PREVIEW_LEN else '')
        out.append(f'  L{sfw_start + i:<5} {preview}')
    out.append(f'')

    # ── Solo-Nude ──
    out.append(f'### NSFW Solo-Nude  L{solo_start}-L{solo_end}  [{len(solo)} entries]')
    out.append(f'')
    for i, line in enumerate(solo):
        preview = line[:PREVIEW_LEN] + ('...' if len(line) > PREVIEW_LEN else '')
        out.append(f'  L{solo_start + i:<5} {preview}')
    out.append(f'')

    # ── Sex (with source annotations) ──
    sex_lines = merged[sex_start - 1:]
    out.append(f'### NSFW Sex  L{sex_start}-L{sex_end}  [{len(sex_lines)} entries]')
    out.append(f'')
    for i, line in enumerate(sex_lines):
        preview = line[:PREVIEW_LEN] + ('...' if len(line) > PREVIEW_LEN else '')
        sources = src_map.get(line, [])
        if sources:
            src_str = ', '.join(f'{c}:L{ln}' for c, ln in sources)
            out.append(f'  L{sex_start + i:<5} {preview}  ← {src_str}')
        else:
            out.append(f'  L{sex_start + i:<5} {preview}  ← [no source — ORPHAN]')
    out.append(f'')

    # ── Category reverse view ──
    out.append(f'---')
    out.append(f'')
    out.append(f'## NSFW Sex Categories (reverse lookup)')
    out.append(f'')
    cat_total = 0
    for fname in sorted(os.listdir(CAT_DIR)):
        if not fname.endswith('.txt'):
            continue
        cat_name = fname.replace('.txt', '')
        fpath = os.path.join(CAT_DIR, fname)
        cat_lines = load_lines(fpath)
        cat_total += len(cat_lines)
        out.append(f'### {cat_name}  [{len(cat_lines)} entries]')
        out.append(f'')
        for i, line in enumerate(cat_lines, 1):
            preview = line[:PREVIEW_LEN] + ('...' if len(line) > PREVIEW_LEN else '')
            # Find merged line number
            try:
                merged_ln = merged.index(line) + 1
                out.append(f'  L{i:<4} → merged:L{merged_ln}  {preview}')
            except ValueError:
                out.append(f'  L{i:<4} → [not in merged]  {preview}')
        out.append(f'')

    out.append(f'Total: {len(merged)} merged entries ({len(sfw)} SFW + {len(solo)} solo + {len(sex_lines)} sex)')
    out.append(f'       {cat_total} subfolder entries (with cross-category duplicates)')

    with open(INDEX_FILE, 'w', encoding='utf-8') as f:
        f.write('\n'.join(out) + '\n')

    print(f'pose_index.txt written: {len(merged)} merged, {cat_total} subfolder entries')


def check():
    """Compare line counts against existing index. Exit 1 if stale."""
    if not os.path.exists(INDEX_FILE):
        print('pose_index.txt not found. Run without --check to generate.')
        sys.exit(1)

    sfw = len(load_lines(SFW_FILE))
    solo = len(load_lines(SOLO_FILE))
    merged = len(load_lines(MERGED_FILE))
    cat_total = sum(
        len(load_lines(os.path.join(CAT_DIR, f)))
        for f in sorted(os.listdir(CAT_DIR)) if f.endswith('.txt')
    )

    with open(INDEX_FILE, 'r', encoding='utf-8') as f:
        content = f.read()

    import re
    m = re.search(r'\[(\d+) entries\]', content.split('---')[0] if '---' in content else content)
    old_merged = int(m.group(1)) if m else -1

    if old_merged != merged:
        print(f'STALE: merged changed ({old_merged} → {merged})')
        sys.exit(1)
    print(f'UP-TO-DATE: {merged} merged, {cat_total} subfolder')
    sys.exit(0)


if __name__ == '__main__':
    if '--check' in sys.argv:
        check()
    else:
        generate()
